import type { Metadata } from "next";
import CookieConsent from "../src/components/CookieConsent";
import Footer from "../src/components/Footer";
import logo from "@/src/img/3d.png";
import Image from "next/image";
import Link from "next/link";
import classes from "./layout.module.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={classes["dashboard-initial-loader"]}>
          <div>
            <Link href={"/"}>
              <Image alt="logo" src={logo}></Image>
            </Link>
          </div>
          <div>
            <h1>GeoSave</h1>
          </div>
          <div className={classes["buttons"]}>
            <Link href="/sign-in" className={classes["btn"]}>
              Sign In
            </Link>
            <Link href="/sign-up" className={classes["btn"]}>
              Sign Up
            </Link>
          </div>
        </div>
        <CookieConsent />
        <main> {children}</main>
        <Footer />
      </body>
    </html>
  );
}
