import type { Metadata } from "next";
import CookieConsent from "../src/components/CookieConsent";
import Footer from "../src/components/Footer";
import { cookies } from "next/headers";
import { verifyToken } from "@/src/lib/jwt";
import { HeaderController } from "../src/components/HeaderController";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  console.log(cookieStore);
  const token = cookieStore.get("jwt")?.value;

  let role = null;

  if (token) {
    try {
      const payload = verifyToken(token);
      role = payload?.role;
    } catch (e) {
      console.error("JWT verification failed:", e);
    }
  }

  return (
    <html lang="en">
      <body>
        <CookieConsent />
        <HeaderController />
        <main> {children}</main>
        <Footer />
      </body>
    </html>
  );
}
